name:         The Digital Journal of Carlos Cuéllar
tagline:      'Standard Nerd'
description:  'A personal blog about design, technology, music and procrastination.'
url:          http://carloscuellar.net
author:       
  name:       'Carlos Cuellar'
  email:      'hola@carloscuellar.net'
markdown:     kramdown
permalink:    /blog/:title/
highlighter:  rouge
paginate:     10
host: 0.0.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      author: "Carlos Cuéllar"
      
# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed