title:         The Digital Journal of Carlos Cuéllar
tagline:      'Standard Nerd'
description:  'A personal blog about design, technology, music and procrastination.'
url:          http://carloscuellar.net
author:
  name:       'Carlos Cuéllar'
  email:      'hola@carloscuellar.net'
markdown:     kramdown
permalink:    /blog/:title/
highlighter:  rouge
paginate:     10
host: 0.0.0.0
twitter:
  username: cuellarfr
logo: /apple-touch-icon-precomposed.png
social:
  name: Carlos Cuellar
  links:
    - https://twitter.com/cuellarfr
    - https://www.linkedin.com/in/cuellarfr
    - https://github.com/cuellarfr
    - https://keybase.io/cuellarfr
webmaster_verifications:
  google: ZTzErRU2qHFONj6qV8Y0t3_ukyx-MtVQzKWwXq0BPLg
  bing: 019F5FD588A9EE4EF990A4653E7E03C3

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "Carlos Cuéllar"

# Use the following plug-ins
plugins:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed
